blank_issues_enabled: false

contact_links:

  - name: ðŸ’¬ Une question ? Ou besoin de parler ?
    url: https://github.com/adouche-design/evomoyenne/discussions
    about: Cliquez ici pour venir dans la discussion evoMoyenne !
